version: '3.8'
services:
  sd-postgres:
    image: postgres
    container_name: sd-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample_db
    ports:
      - 5432:5432
    volumes:
      - ./sd-pg:/var/lib/postgresql/data
